config/routes.rb
Overrealm::Application.routes.draw do

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  
  devise_for :users
  
  resources :users, :only => [:show, :index]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks

  rolify

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h3 Home
- @users.each do |user|
  %p
    User: #{link_to user.name, user}

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "flash-alert alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
= link_to "Overrealm", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path
    - if current_user.has_role? :admin
      %li
        = link_to 'Admin', users_path
  - else
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/_navigation_bottom.html.haml
= link_to "Overrealm", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path
    - if current_user.has_role? :admin
      %li
        = link_to 'Admin', users_path
  - else
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/_navigation_top.html.haml
= link_to "OverRealm", root_path, :class => 'brand'
%ul.nav.pull-right
  - if user_signed_in?
    %li.dropdown
      = link_to '#', :class => 'dropdown-toggle', 'data-toggle' => 'dropdown' do
        sign in
        %b.caret
      %ul.dropdown-menu
        %li
          = link_to 'Logout', destroy_user_session_path, :method=>'delete'
        %li
          = link_to 'Edit account', edit_user_registration_path
        - if current_user.has_role? :admin
          %li
            = link_to 'Admin', users_path
  - else
    %li.dropdown
      = link_to '#', :class => 'dropdown-toggle', 'data-toggle' => 'dropdown' do
        sign in
        %b.caret
      %ul.dropdown-menu
        %li
          = link_to 'Sign in', new_user_session_path
        %li
          = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Overrealm"
      %meta{:content => content_for?(:description) ? yield(:description) : "Overrealm", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body
    %header.navbar.navbar-fixed-top.navbar-inverse
      %nav.navbar-inner
        .container-fluid
          = render 'layouts/navigation_top'
    #main{:role => "main"}
      .container-fluid
        .row-fluid
          .span12
            = render 'layouts/messages'
            = yield
    %footer.navbar.navbar-fixed-bottom
      %nav.navbar-inner
        .container-fluid
          = render 'layouts/navigation_bottom'

app/views/users/index.html.haml
%h3 Users
%ul.users
  - @users.each do |user|
    %li
      = link_to user.name, user
      signed up #{user.created_at.to_date}

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}